# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
ItemTag.destroy_all
Tag.destroy_all
Item.destroy_all
List.destroy_all


camping_tag = Tag.create!(category: 'Camping')
hiking_tag = Tag.create!(category: 'Hiking')
climbing_tag = Tag.create!(category: 'Climbing')
kayaking_tag = Tag.create!(category: 'Kayaking')
mtn_bike_tag = Tag.create!(category: 'Mountain Biking')
backpacking_tag = Tag.create!(category: 'Backpacking')
fishing_tag = Tag.create!(category: 'Fishing')
everything = Tag.create!(category: 'Everything')

# CAMPING ITEMS
folding_table = camping_tag.items.create!(name: 'Folding Table')
ItemTag.create!(item: folding_table, tag: everything)
flashlight = camping_tag.items.create!(name: 'Flashlight')
ItemTag.create!(item: flashlight, tag: everything)
duct_tape = camping_tag.items.create!(name: 'Duct Tape')
ItemTag.create!(item: duct_tape, tag: everything)
air_mattress = camping_tag.items.create!(name: 'Air Mattress')
ItemTag.create!(item: air_mattress, tag: everything)
pillow = camping_tag.items.create!(name: 'Pillow')
ItemTag.create!(item: pillow, tag: everything)
blankets = camping_tag.items.create!(name: 'Blankets')
ItemTag.create!(item: blankets, tag: everything)
camp_stove = camping_tag.items.create!(name: 'Camp Stove')
ItemTag.create!(item: camp_stove, tag: everything)
firewood = camping_tag.items.create!(name: 'Firewood')
ItemTag.create!(item: firewood, tag: everything)
grill_grate = camping_tag.items.create!(name: 'Grill Grate')
ItemTag.create!(item: grill_grate, tag: everything)
water_bucket = camping_tag.items.create!(name: 'Water Bucket')
ItemTag.create!(item: water_bucket, tag: everything)
plates = camping_tag.items.create!(name: 'Plates')
ItemTag.create!(item: plates, tag: everything)
cups = camping_tag.items.create!(name: 'Cups')
ItemTag.create!(item: cups, tag: everything)
portable_coffee_maker = camping_tag.items.create!(name: 'Portable Coffee Maker')
ItemTag.create!(item: portable_coffee_maker, tag: everything)
campsite_games = camping_tag.items.create!(name: 'Campsite Games')
ItemTag.create!(item: campsite_games, tag: everything)
smores = camping_tag.items.create!(name: 'Smores')
ItemTag.create!(item: smores, tag: everything)
prepared_meals = camping_tag.items.create!(name: 'Prepared Meals')
ItemTag.create!(item: prepared_meals, tag: everything)

#CAMPING/BACKPACKING ITEMS
tent = Item.create!(name: 'Tent')
ItemTag.create!(item: tent, tag: camping_tag)
ItemTag.create!(item: tent, tag: backpacking_tag)
ItemTag.create!(item: tent, tag: everything)

stakes = Item.create!(name: 'Stakes')
ItemTag.create!(item: stakes, tag: camping_tag)
ItemTag.create!(item: stakes, tag: backpacking_tag)
ItemTag.create!(item: stakes, tag: everything)

tent_repair_kit = Item.create!(name: 'Tent Repair Kit')
ItemTag.create!(item: tent_repair_kit, tag: camping_tag)
ItemTag.create!(item: tent_repair_kit, tag: backpacking_tag)
ItemTag.create!(item: tent_repair_kit, tag: everything)

sleeping_bag = Item.create!(name: 'Sleeping Bag')
ItemTag.create!(item: sleeping_bag, tag: camping_tag)
ItemTag.create!(item: sleeping_bag, tag: backpacking_tag)
ItemTag.create!(item: sleeping_bag, tag: everything)

sleeping_pad = Item.create!(name: 'Sleeping Pad')
ItemTag.create!(item: sleeping_pad, tag: camping_tag)
ItemTag.create!(item: sleeping_pad, tag: backpacking_tag)
ItemTag.create!(item: sleeping_pad, tag: everything)

jet_boil = Item.create!(name: 'Jet Boil')
ItemTag.create!(item: jet_boil, tag: camping_tag)
ItemTag.create!(item: jet_boil, tag: backpacking_tag)
ItemTag.create!(item: jet_boil, tag: everything)

fuel = Item.create!(name: 'Fuel')
ItemTag.create!(item: fuel, tag: camping_tag)
ItemTag.create!(item: fuel, tag: backpacking_tag)
ItemTag.create!(item: fuel, tag: everything)

fire_starter = Item.create!(name: 'Fire Starter')
ItemTag.create!(item: fire_starter, tag: camping_tag)
ItemTag.create!(item: fire_starter, tag: backpacking_tag)
ItemTag.create!(item: fire_starter, tag: everything)

cooking_utensils = Item.create!(name: 'Cooking Utensils')
ItemTag.create!(item: cooking_utensils, tag: camping_tag)
ItemTag.create!(item: cooking_utensils, tag: backpacking_tag)
ItemTag.create!(item: cooking_utensils, tag: everything)

durable_mug = Item.create!(name: 'Durable Mug')
ItemTag.create!(item: durable_mug, tag: camping_tag)
ItemTag.create!(item: durable_mug, tag: backpacking_tag)
ItemTag.create!(item: durable_mug, tag: everything)

collapsible_bowls = Item.create!(name: 'Collapsible Bowls')
ItemTag.create!(item: collapsible_bowls, tag: camping_tag)
ItemTag.create!(item: collapsible_bowls, tag: backpacking_tag)
ItemTag.create!(item: collapsible_bowls, tag: everything)

shovel = Item.create!(name: 'Shovel')
ItemTag.create!(item: shovel, tag: camping_tag)
ItemTag.create!(item: shovel, tag: backpacking_tag)
ItemTag.create!(item: shovel, tag: everything)

toiletries = Item.create!(name: 'Toiletries')
ItemTag.create!(item: toiletries, tag: camping_tag)
ItemTag.create!(item: toiletries, tag: backpacking_tag)
ItemTag.create!(item: toiletries, tag: everything)

deck_of_cards = Item.create!(name: 'Deck of Cards')
ItemTag.create!(item: deck_of_cards, tag: camping_tag)
ItemTag.create!(item: deck_of_cards, tag: backpacking_tag)
ItemTag.create!(item: deck_of_cards, tag: everything)

paracord = Item.create!(name: 'Paracord')
ItemTag.create!(item: paracord, tag: camping_tag)
ItemTag.create!(item: paracord, tag: backpacking_tag)
ItemTag.create!(item: paracord, tag: everything)

camping_hammock = Item.create!(name: 'Camping Hammock')
ItemTag.create!(item: camping_hammock, tag: camping_tag)
ItemTag.create!(item: camping_hammock, tag: backpacking_tag)
ItemTag.create!(item: camping_hammock, tag: everything)

thermal_underwear = Item.create!(name: 'Thermal Underwear')
ItemTag.create!(item: thermal_underwear, tag: camping_tag)
ItemTag.create!(item: thermal_underwear, tag: backpacking_tag)
ItemTag.create!(item: thermal_underwear, tag: everything)

carabiners = Item.create!(name: 'Carabiners')
ItemTag.create!(item: carabiners, tag: camping_tag)
ItemTag.create!(item: carabiners, tag: backpacking_tag)
ItemTag.create!(item: carabiners, tag: everything)

trash_bag = Item.create!(name: 'Trash Bag')
ItemTag.create!(item: trash_bag, tag: camping_tag)
ItemTag.create!(item: trash_bag, tag: backpacking_tag)
ItemTag.create!(item: trash_bag, tag: everything)


# BACKPACKING ITEMS
bear_resistant_canister = backpacking_tag.items.create!(name: 'Bear Resistant Canister')
ItemTag.create!(item: bear_resistant_canister, tag: everything)
bear_spray = backpacking_tag.items.create!(name: 'Bear Spray')
ItemTag.create!(item: bear_spray, tag: everything)
dehydrated_meals = backpacking_tag.items.create!(name: 'Dehydrated Meals')
ItemTag.create!(item: dehydrated_meals, tag: everything)
dried_foods = backpacking_tag.items.create!(name: 'Dried Foods')
ItemTag.create!(item: dried_foods, tag: everything)
satellite_communicator = backpacking_tag.items.create!(name: 'Satellite Communicator')
ItemTag.create!(item: satellite_communicator, tag: everything)
water_filtration_system = backpacking_tag.items.create!(name: 'Water Filtration System')
ItemTag.create!(item: water_filtration_system, tag: everything)


# FISHING ITEMS
fishing_license = fishing_tag.items.create!(name: 'Fishing License')
ItemTag.create!(item: fishing_license, tag: everything)
fishing_hooks = fishing_tag.items.create!(name: 'Fishing Hooks')
ItemTag.create!(item: fishing_hooks, tag: everything)
hook_remover = fishing_tag.items.create!(name: 'Hook Remover')
ItemTag.create!(item: hook_remover, tag: everything)
fishing_line = fishing_tag.items.create!(name: 'Fishing Line')
ItemTag.create!(item: fishing_line, tag: everything)
fishing_net = fishing_tag.items.create!(name: 'Fishing Net')
ItemTag.create!(item: fishing_net, tag: everything)
fishing_reel = fishing_tag.items.create!(name: 'Fishing Reel')
ItemTag.create!(item: fishing_reel, tag: everything)
fishing_rod = fishing_tag.items.create!(name: 'Fishing Pole')
ItemTag.create!(item: fishing_rod, tag: everything)
fishing_vest = fishing_tag.items.create!(name: 'Fishing Vest')
ItemTag.create!(item: fishing_vest, tag: everything)
sinkers = fishing_tag.items.create!(name: 'Sinkers')
ItemTag.create!(item: sinkers, tag: everything)
bobbers = fishing_tag.items.create!(name: 'Bobbers')
ItemTag.create!(item: bobbers, tag: everything)
swivels = fishing_tag.items.create!(name: 'Swivels')
ItemTag.create!(item: swivels, tag: everything)
snaps = fishing_tag.items.create!(name: 'Snaps')
ItemTag.create!(item: snaps, tag: everything)
lures = fishing_tag.items.create!(name: 'Lures')
ItemTag.create!(item: lures, tag: everything)
live_bait = fishing_tag.items.create!(name: 'Live Bait')
ItemTag.create!(item: live_bait, tag: everything)
bait_alternatives = fishing_tag.items.create!(name: 'Bait Alternatives')
ItemTag.create!(item: bait_alternatives, tag: everything)
tackle_box = fishing_tag.items.create!(name: 'Tackle Box')
ItemTag.create!(item: tackle_box, tag: everything)
gaiters = fishing_tag.items.create!(name: 'Gaiters')
ItemTag.create!(item: gaiters, tag: everything)
pliers = fishing_tag.items.create!(name: 'Pliers')
ItemTag.create!(item: pliers, tag: everything)


# CLIMBING ITEMS
climbing_shoes = climbing_tag.items.create!(name: 'Climbing Shoes')
ItemTag.create!(item: climbing_shoes, tag: everything )
approach_shoes = climbing_tag.items.create!(name: 'Approach Shoes')
ItemTag.create!(item: approach_shoes, tag: everything)
chalk_bag = climbing_tag.items.create!(name: 'Chalk Bag')
ItemTag.create!(item: chalk_bag, tag: everything)
chalk = climbing_tag.items.create!(name: 'Chalk')
ItemTag.create!(item: chalk, tag: everything)
harness = climbing_tag.items.create!(name: 'Harness')
ItemTag.create!(item: harness, tag: everything)
belay_device = climbing_tag.items.create!(name: 'Belay Device')
ItemTag.create!(item: belay_device, tag: everything)
locking_carabiner = climbing_tag.items.create!(name: 'Locking Carabiner')
ItemTag.create!(item: locking_carabiner, tag: everything)
non_locking_carabiner = climbing_tag.items.create!(name: 'Non-Locking Carabiner')
ItemTag.create!(item: non_locking_carabiner, tag: everything)
climbing_rope = climbing_tag.items.create!(name: 'Climbing Rope')
ItemTag.create!(item: climbing_rope, tag: everything)
slings = climbing_tag.items.create!(name: 'Slings')
ItemTag.create!(item: slings, tag: everything)
quickdraws = climbing_tag.items.create!(name: 'Quickdraws')
ItemTag.create!(item: quickdraws, tag: everything)
cams = climbing_tag.items.create!(name: 'Cams')
ItemTag.create!(item: cams, tag: everything)
nuts = climbing_tag.items.create!(name: 'Nuts')
ItemTag.create!(item: nuts, tag: everything)
hexes = climbing_tag.items.create!(name: 'Hexes')
ItemTag.create!(item: hexes, tag: everything)
ascenders = climbing_tag.items.create!(name: 'Ascenders')
ItemTag.create!(item: ascenders, tag: everything)
descenders = climbing_tag.items.create!(name: 'Descenders')
ItemTag.create!(item: descenders, tag: everything)
personal_anchor_system = climbing_tag.items.create!(name: 'Personal Anchor System')
ItemTag.create!(item: personal_anchor_system, tag: everything)


# KAYAKING ITEMS
kayak = kayaking_tag.items.create!(name: 'Kayak')
ItemTag.create!(item: kayak, tag: everything)
paddle = kayaking_tag.items.create!(name: 'Paddle')
ItemTag.create!(item: paddle, tag: everything)
spray_skirt = kayaking_tag.items.create!(name: 'Spray Skirt')
ItemTag.create!(item: spray_skirt, tag: everything)
bilge_pump = kayaking_tag.items.create!(name: 'Bilge Pump')
ItemTag.create!(item: bilge_pump, tag: everything)
paddle_leash = kayaking_tag.items.create!(name: 'Paddle Leash')
ItemTag.create!(item: paddle_leash, tag: everything)
kayak_repair_kit = kayaking_tag.items.create!(name: 'Kayak Repair Kit')
ItemTag.create!(item: kayak_repair_kit, tag: everything)
throw_rope = kayaking_tag.items.create!(name: 'Throw Rope')
ItemTag.create!(item: throw_rope, tag: everything)


# MOUNTAIN BIKING ITEMS
mountain_bike = mtn_bike_tag.items.create!(name: 'Mountain Bike')
ItemTag.create!(item: mountain_bike, tag: everything)
bike_shoes = mtn_bike_tag.items.create!(name: 'Bike Shoes')
ItemTag.create!(item: bike_shoes, tag: everything)
platform_pedals = mtn_bike_tag.items.create!(name: 'Platform Pedals')
ItemTag.create!(item: platform_pedals, tag: everything)
clipless_pedals = mtn_bike_tag.items.create!(name: 'Clipless Pedals')
ItemTag.create!(item: clipless_pedals, tag: everything)
spare_tubes = mtn_bike_tag.items.create!(name: 'Spare Tubes')
ItemTag.create!(item: spare_tubes, tag: everything)
tubeless_repair_kit = mtn_bike_tag.items.create!(name: 'Tubeless Repair Kit')
ItemTag.create!(item: tubeless_repair_kit, tag: everything)
tire_pump = mtn_bike_tag.items.create!(name: 'Tire Pump')
ItemTag.create!(item: tire_pump, tag: everything)
tire_levers = mtn_bike_tag.items.create!(name: 'Tire Levers')
ItemTag.create!(item: tire_levers, tag: everything)
chain_tool = mtn_bike_tag.items.create!(name: 'Chain Tool')
ItemTag.create!(item: chain_tool, tag: everything)
spare_chain_links = mtn_bike_tag.items.create!(name: 'Spare Chain Links')
ItemTag.create!(item: spare_chain_links, tag: everything)
chain_lubricant = mtn_bike_tag.items.create!(name: 'Chain Lubricant')
ItemTag.create!(item: chain_lubricant, tag: everything)
suspension_pump = mtn_bike_tag.items.create!(name: 'Suspension Pump')
ItemTag.create!(item: suspension_pump, tag: everything)
bike_lock = mtn_bike_tag.items.create!(name: 'Bike Lock')
ItemTag.create!(item: bike_lock, tag: everything)
bike_lights = mtn_bike_tag.items.create!(name: 'Bike Lights')
ItemTag.create!(item: bike_lights, tag: everything)
padded_cycling_shorts = mtn_bike_tag.items.create!(name: 'Padded Cycling Shorts')
ItemTag.create!(item: padded_cycling_shorts, tag: everything)
cycling_socks = mtn_bike_tag.items.create!(name: 'Cycling Socks')
ItemTag.create!(item: cycling_socks, tag: everything)
knee_pads = mtn_bike_tag.items.create!(name: 'Knee Pads')
ItemTag.create!(item: knee_pads, tag: everything)
elbow_pads = mtn_bike_tag.items.create!(name: 'Elbow Pads')
ItemTag.create!(item: elbow_pads, tag: everything)
bike_bell = mtn_bike_tag.items.create!(name: 'Bike Bell')
ItemTag.create!(item: bike_bell, tag: everything)
reflective_gear = mtn_bike_tag.items.create!(name: 'Reflective Gear')
ItemTag.create!(item: reflective_gear, tag: everything)
bike_repair_instructions = mtn_bike_tag.items.create!(name: 'Bike Repair Instructions')
ItemTag.create!(item: bike_repair_instructions, tag: everything)

# food/water
water = Item.create!(name: 'Water')
ItemTag.create!(item: water, tag: camping_tag)
ItemTag.create!(item: water, tag: hiking_tag)
ItemTag.create!(item: water, tag: fishing_tag)
ItemTag.create!(item: water, tag: climbing_tag)
ItemTag.create!(item: water, tag: kayaking_tag)
ItemTag.create!(item: water, tag: mtn_bike_tag)
ItemTag.create!(item: water, tag: backpacking_tag)
ItemTag.create!(item: water, tag: everything)

snacks = Item.create!(name: 'Snacks')
ItemTag.create!(item: snacks, tag: camping_tag)
ItemTag.create!(item: snacks, tag: hiking_tag)
ItemTag.create!(item: snacks, tag: fishing_tag)
ItemTag.create!(item: snacks, tag: climbing_tag)
ItemTag.create!(item: snacks, tag: kayaking_tag)
ItemTag.create!(item: snacks, tag: mtn_bike_tag)
ItemTag.create!(item: snacks, tag: everything)

energy_bars = Item.create!(name: 'Energy Bars')
ItemTag.create!(item: energy_bars, tag: camping_tag)
ItemTag.create!(item: energy_bars, tag: hiking_tag)
ItemTag.create!(item: energy_bars, tag: fishing_tag)
ItemTag.create!(item: energy_bars, tag: climbing_tag)
ItemTag.create!(item: energy_bars, tag: kayaking_tag)
ItemTag.create!(item: energy_bars, tag: mtn_bike_tag)
ItemTag.create!(item: energy_bars, tag: backpacking_tag)
ItemTag.create!(item: energy_bars, tag: everything)

# ALL TAGS ITEMS
sunscreen = Item.create!(name: 'Sunscreen')
ItemTag.create!(item: sunscreen, tag: camping_tag)
ItemTag.create!(item: sunscreen, tag: hiking_tag)
ItemTag.create!(item: sunscreen, tag: fishing_tag)
ItemTag.create!(item: sunscreen, tag: climbing_tag)
ItemTag.create!(item: sunscreen, tag: kayaking_tag)
ItemTag.create!(item: sunscreen, tag: mtn_bike_tag)
ItemTag.create!(item: sunscreen, tag: backpacking_tag)
ItemTag.create!(item: sunscreen, tag: everything)

lip_balm = Item.create!(name: 'Lip Balm')
ItemTag.create!(item: lip_balm, tag: camping_tag)
ItemTag.create!(item: lip_balm, tag: hiking_tag)
ItemTag.create!(item: lip_balm, tag: fishing_tag)
ItemTag.create!(item: lip_balm, tag: climbing_tag)
ItemTag.create!(item: lip_balm, tag: kayaking_tag)
ItemTag.create!(item: lip_balm, tag: mtn_bike_tag)
ItemTag.create!(item: lip_balm, tag: backpacking_tag)
ItemTag.create!(item: lip_balm, tag: everything)

waterproof_bag = Item.create!(name: 'Waterproof Bag')
ItemTag.create!(item: waterproof_bag, tag: camping_tag)
ItemTag.create!(item: waterproof_bag, tag: hiking_tag)
ItemTag.create!(item: waterproof_bag, tag: fishing_tag)
ItemTag.create!(item: waterproof_bag, tag: climbing_tag)
ItemTag.create!(item: waterproof_bag, tag: kayaking_tag)
ItemTag.create!(item: waterproof_bag, tag: mtn_bike_tag)
ItemTag.create!(item: waterproof_bag, tag: backpacking_tag)
ItemTag.create!(item: waterproof_bag, tag: everything)

gloves = Item.create!(name: 'Gloves')
ItemTag.create!(item: gloves, tag: camping_tag)
ItemTag.create!(item: gloves, tag: hiking_tag)
ItemTag.create!(item: gloves, tag: fishing_tag)
ItemTag.create!(item: gloves, tag: climbing_tag)
ItemTag.create!(item: gloves, tag: kayaking_tag)
ItemTag.create!(item: gloves, tag: mtn_bike_tag)
ItemTag.create!(item: gloves, tag: backpacking_tag)
ItemTag.create!(item: gloves, tag: everything)

towel = Item.create!(name: 'Towel')
ItemTag.create!(item: towel, tag: camping_tag)
ItemTag.create!(item: towel, tag: hiking_tag)
ItemTag.create!(item: towel, tag: fishing_tag)
ItemTag.create!(item: towel, tag: climbing_tag)
ItemTag.create!(item: towel, tag: kayaking_tag)
ItemTag.create!(item: towel, tag: mtn_bike_tag)
ItemTag.create!(item: towel, tag: backpacking_tag)
item_tag = ItemTag.create!(item: towel, tag: everything)

# Sport
helmet = Item.create!(name: 'Helmet')
ItemTag.create!(item: helmet, tag: climbing_tag)
ItemTag.create!(item: helmet, tag: kayaking_tag)
ItemTag.create!(item: helmet, tag: mtn_bike_tag)
ItemTag.create!(item: helmet, tag: everything)

# Aquatic
life_jacket = Item.create!(name: 'Life Jacket')
ItemTag.create!(item: life_jacket, tag: fishing_tag)
ItemTag.create!(item: life_jacket, tag: kayaking_tag)
ItemTag.create!(item: life_jacket, tag: everything)

water_shoes = Item.create!(name: 'Water Shoes')
ItemTag.create!(item: water_shoes, tag: camping_tag)
ItemTag.create!(item: water_shoes, tag: fishing_tag)
ItemTag.create!(item: water_shoes, tag: kayaking_tag)
ItemTag.create!(item: water_shoes, tag: everything)

sandals = Item.create!(name: 'Sandals')
ItemTag.create!(item: sandals, tag: camping_tag)
ItemTag.create!(item: sandals, tag: fishing_tag)
ItemTag.create!(item: sandals, tag: kayaking_tag)
ItemTag.create!(item: sandals, tag: everything)

swimwear = Item.create!(name: 'Swimwear')
ItemTag.create!(item: swimwear, tag: camping_tag)
ItemTag.create!(item: swimwear, tag: fishing_tag)
ItemTag.create!(item: swimwear, tag: kayaking_tag)
ItemTag.create!(item: swimwear, tag: backpacking_tag)
ItemTag.create!(item: swimwear, tag: everything)

# outdoorsy ITEMS
cooler = Item.create!(name: 'Cooler')
ItemTag.create!(item: cooler, tag: camping_tag)
ItemTag.create!(item: cooler, tag: fishing_tag)
ItemTag.create!(item: cooler, tag: backpacking_tag)
ItemTag.create!(item: cooler, tag: everything)

camp_chair = Item.create!(name: 'Camp Chair')
ItemTag.create!(item: camp_chair, tag: camping_tag)
ItemTag.create!(item: camp_chair, tag: fishing_tag)
ItemTag.create!(item: camp_chair, tag: backpacking_tag)
ItemTag.create!(item: camp_chair, tag: everything)

cleaning_supplies = Item.create!(name: 'Cleaning Supplies')
ItemTag.create!(item: cleaning_supplies, tag: camping_tag)
ItemTag.create!(item: cleaning_supplies, tag: fishing_tag)
ItemTag.create!(item: cleaning_supplies, tag: backpacking_tag)
ItemTag.create!(item: cleaning_supplies, tag: everything)

# Clothing
hiking_boots = Item.create!(name: 'Hiking Boots')
ItemTag.create!(item: hiking_boots, tag: camping_tag)
ItemTag.create!(item: hiking_boots, tag: hiking_tag)
ItemTag.create!(item: hiking_boots, tag: backpacking_tag)
ItemTag.create!(item: hiking_boots, tag: everything)

weather_appropriate_clothing = Item.create!(name: 'Weather Appropriate Clothing')
ItemTag.create!(item: weather_appropriate_clothing, tag: camping_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: hiking_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: fishing_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: climbing_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: kayaking_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: mtn_bike_tag)
ItemTag.create!(item: weather_appropriate_clothing, tag: backpacking_tag)
item_tag = ItemTag.create!(item: weather_appropriate_clothing, tag: everything)

extra_layers = Item.create!(name: 'Extra Layers')
ItemTag.create!(item: extra_layers, tag: camping_tag)
ItemTag.create!(item: extra_layers, tag: hiking_tag)
ItemTag.create!(item: extra_layers, tag: fishing_tag)
ItemTag.create!(item: extra_layers, tag: climbing_tag)
ItemTag.create!(item: extra_layers, tag: kayaking_tag)
ItemTag.create!(item: extra_layers, tag: mtn_bike_tag)
ItemTag.create!(item: extra_layers, tag: everything)

insulating_layers = Item.create!(name: 'Insulating Layers')
ItemTag.create!(item: insulating_layers, tag: camping_tag)
ItemTag.create!(item: insulating_layers, tag: hiking_tag)
ItemTag.create!(item: insulating_layers, tag: fishing_tag)
ItemTag.create!(item: insulating_layers, tag: climbing_tag)
ItemTag.create!(item: insulating_layers, tag: kayaking_tag)
ItemTag.create!(item: insulating_layers, tag: mtn_bike_tag)
ItemTag.create!(item: insulating_layers, tag: backpacking_tag)
ItemTag.create!(item: insulating_layers, tag: everything)


quick_dry_clothing = Item.create!(name: 'Quick Dry Clothing')
ItemTag.create!(item: quick_dry_clothing, tag: camping_tag)
ItemTag.create!(item: quick_dry_clothing, tag: hiking_tag)
ItemTag.create!(item: quick_dry_clothing, tag: fishing_tag)
ItemTag.create!(item: quick_dry_clothing, tag: climbing_tag)
ItemTag.create!(item: quick_dry_clothing, tag: kayaking_tag)
ItemTag.create!(item: quick_dry_clothing, tag: mtn_bike_tag)
ItemTag.create!(item: quick_dry_clothing, tag: backpacking_tag)
ItemTag.create!(item: quick_dry_clothing, tag: everything)


rain_gear = Item.create!(name: 'Rain Gear')
ItemTag.create!(item: rain_gear, tag: camping_tag)
ItemTag.create!(item: rain_gear, tag: hiking_tag)
ItemTag.create!(item: rain_gear, tag: fishing_tag)
ItemTag.create!(item: rain_gear, tag: climbing_tag)
ItemTag.create!(item: rain_gear, tag: kayaking_tag)
ItemTag.create!(item: rain_gear, tag: mtn_bike_tag)
ItemTag.create!(item: rain_gear, tag: backpacking_tag)
ItemTag.create!(item: rain_gear, tag: everything)

hat = Item.create!(name: 'Hat')
ItemTag.create!(item: hat, tag: camping_tag)
ItemTag.create!(item: hat, tag: hiking_tag)
ItemTag.create!(item: hat, tag: fishing_tag)
ItemTag.create!(item: hat, tag: climbing_tag)
ItemTag.create!(item: hat, tag: kayaking_tag)
ItemTag.create!(item: hat, tag: mtn_bike_tag)
ItemTag.create!(item: hat, tag: backpacking_tag)
ItemTag.create!(item: hat, tag: everything)

sunglasses = Item.create!(name: 'Sunglasses')
ItemTag.create!(item: sunglasses, tag: camping_tag)
ItemTag.create!(item: sunglasses, tag: hiking_tag)
ItemTag.create!(item: sunglasses, tag: fishing_tag)
ItemTag.create!(item: sunglasses, tag: climbing_tag)
ItemTag.create!(item: sunglasses, tag: kayaking_tag)
ItemTag.create!(item: sunglasses, tag: mtn_bike_tag)
ItemTag.create!(item: sunglasses, tag: backpacking_tag)
ItemTag.create!(item: sunglasses, tag: everything)

#misc
backpack = Item.create!(name: 'Backpack')
ItemTag.create!(item: backpack, tag: camping_tag)
ItemTag.create!(item: backpack, tag: hiking_tag)
ItemTag.create!(item: backpack, tag: mtn_bike_tag)
ItemTag.create!(item: backpack, tag: backpacking_tag)
ItemTag.create!(item: backpack, tag: everything)

water_bottle = Item.create!(name: 'Water Bottle')
ItemTag.create!(item: water_bottle, tag: camping_tag)
ItemTag.create!(item: water_bottle, tag: hiking_tag)
ItemTag.create!(item: water_bottle, tag: fishing_tag)
ItemTag.create!(item: water_bottle, tag: climbing_tag)
ItemTag.create!(item: water_bottle, tag: kayaking_tag)
ItemTag.create!(item: water_bottle, tag: mtn_bike_tag)
ItemTag.create!(item: water_bottle, tag: backpacking_tag)
ItemTag.create!(item: water_bottle, tag: everything)

trekking_poles = Item.create!(name: 'Trekking Poles')
insect_repellent = Item.create!(name: 'Insect Repellent')
camera = Item.create!(name: 'Camera')
cash = Item.create!(name: 'Cash')
credit_cards = Item.create!(name: 'Credit Cards')

personal_identification = Item.create!(name: 'Personal Identification')
portable_phone_charger = Item.create!(name: 'Portable Phone Charger')
phone = Item.create!(name: 'Phone')
binoculars = Item.create!(name: 'Binoculars')


# safety
first_aid_kit = Item.create!(name: 'First Aid Kit')
ItemTag.create!(item: first_aid_kit, tag: camping_tag)
ItemTag.create!(item: first_aid_kit, tag: hiking_tag)
ItemTag.create!(item: first_aid_kit, tag: fishing_tag)
ItemTag.create!(item: first_aid_kit, tag: climbing_tag)
ItemTag.create!(item: first_aid_kit, tag: kayaking_tag)
ItemTag.create!(item: first_aid_kit, tag: mtn_bike_tag)
ItemTag.create!(item: first_aid_kit, tag: backpacking_tag)
ItemTag.create!(item: first_aid_kit, tag: everything)

map = Item.create!(name: 'Map')
ItemTag.create!(item: map, tag: camping_tag)
ItemTag.create!(item: map, tag: hiking_tag)
ItemTag.create!(item: map, tag: fishing_tag)
ItemTag.create!(item: map, tag: climbing_tag)
ItemTag.create!(item: map, tag: kayaking_tag)
ItemTag.create!(item: map, tag: mtn_bike_tag)
ItemTag.create!(item: map, tag: backpacking_tag)
ItemTag.create!(item: map, tag: everything)

personal_locator_beacon = Item.create!(name: 'Personal Locator Beacon')
ItemTag.create!(item: personal_locator_beacon, tag: climbing_tag)
ItemTag.create!(item: personal_locator_beacon, tag: kayaking_tag)
ItemTag.create!(item: personal_locator_beacon, tag: mtn_bike_tag)
ItemTag.create!(item: personal_locator_beacon, tag: backpacking_tag)
ItemTag.create!(item: personal_locator_beacon, tag: everything)

compass = Item.create!(name: 'Compass')

gps_device = Item.create!(name: 'GPS Device')
ItemTag.create!(item: gps_device, tag: camping_tag)
ItemTag.create!(item: gps_device, tag: hiking_tag)
ItemTag.create!(item: gps_device, tag: fishing_tag)
ItemTag.create!(item: gps_device, tag: climbing_tag)
ItemTag.create!(item: gps_device, tag: kayaking_tag)
ItemTag.create!(item: gps_device, tag: mtn_bike_tag)
ItemTag.create!(item: gps_device, tag: backpacking_tag)
ItemTag.create!(item: gps_device, tag: everything)

medications = Item.create!(name: 'Medications')
ItemTag.create!(item: medications, tag: camping_tag)
ItemTag.create!(item: medications, tag: hiking_tag)
ItemTag.create!(item: medications, tag: fishing_tag)
ItemTag.create!(item: medications, tag: climbing_tag)
ItemTag.create!(item: medications, tag: kayaking_tag)
ItemTag.create!(item: medications, tag: mtn_bike_tag)
ItemTag.create!(item: medications, tag: backpacking_tag)
ItemTag.create!(item: medications, tag: everything)

multi_tool = Item.create!(name: 'Multi-Tool')
ItemTag.create!(item: multi_tool, tag: camping_tag)
ItemTag.create!(item: multi_tool, tag: hiking_tag)
ItemTag.create!(item: multi_tool, tag: fishing_tag)
ItemTag.create!(item: multi_tool, tag: climbing_tag)
ItemTag.create!(item: multi_tool, tag: kayaking_tag)
ItemTag.create!(item: multi_tool, tag: mtn_bike_tag)
ItemTag.create!(item: multi_tool, tag: backpacking_tag)
ItemTag.create!(item: multi_tool, tag: everything)

knife = Item.create!(name: 'Knife')
ItemTag.create!(item: knife, tag: camping_tag)
ItemTag.create!(item: knife, tag: hiking_tag)
ItemTag.create!(item: knife, tag: fishing_tag)
ItemTag.create!(item: knife, tag: climbing_tag)
ItemTag.create!(item: knife, tag: kayaking_tag)
ItemTag.create!(item: knife, tag: mtn_bike_tag)
ItemTag.create!(item: knife, tag: backpacking_tag)
ItemTag.create!(item: knife, tag: everything)

whistle = Item.create!(name: 'Whistle')
ItemTag.create!(item: whistle, tag: camping_tag)
ItemTag.create!(item: whistle, tag: hiking_tag)
ItemTag.create!(item: whistle, tag: fishing_tag)
ItemTag.create!(item: whistle, tag: climbing_tag)
ItemTag.create!(item: whistle, tag: kayaking_tag)
ItemTag.create!(item: whistle, tag: mtn_bike_tag)
ItemTag.create!(item: whistle, tag: backpacking_tag)
ItemTag.create!(item: whistle, tag: everything)

route_description = Item.create!(name: 'Route Description')
ItemTag.create!(item: route_description, tag: camping_tag)
ItemTag.create!(item: route_description, tag: hiking_tag)
ItemTag.create!(item: route_description, tag: fishing_tag)
ItemTag.create!(item: route_description, tag: climbing_tag)
ItemTag.create!(item: route_description, tag: kayaking_tag)
ItemTag.create!(item: route_description, tag: mtn_bike_tag)
ItemTag.create!(item: route_description, tag: backpacking_tag)
ItemTag.create!(item: route_description, tag: everything)

guide_book = Item.create!(name: 'Guide Book')
ItemTag.create!(item: guide_book, tag: camping_tag)
ItemTag.create!(item: guide_book, tag: hiking_tag)
ItemTag.create!(item: guide_book, tag: fishing_tag)
ItemTag.create!(item: guide_book, tag: climbing_tag)
ItemTag.create!(item: guide_book, tag: kayaking_tag)
ItemTag.create!(item: guide_book, tag: mtn_bike_tag)
ItemTag.create!(item: guide_book, tag: backpacking_tag)
ItemTag.create!(item: guide_book, tag: everything)

permits = Item.create!(name: 'Permits')
ItemTag.create!(item: permits, tag: fishing_tag)
ItemTag.create!(item: permits, tag: climbing_tag)
ItemTag.create!(item: permits, tag: kayaking_tag)
ItemTag.create!(item: permits, tag: mtn_bike_tag)
ItemTag.create!(item: permits, tag: backpacking_tag)
ItemTag.create!(item: permits, tag: everything)

batteries = Item.create!(name: 'Batteries')
ItemTag.create!(item: batteries, tag: camping_tag)
ItemTag.create!(item: batteries, tag: hiking_tag)
ItemTag.create!(item: batteries, tag: fishing_tag)
ItemTag.create!(item: batteries, tag: climbing_tag)
ItemTag.create!(item: batteries, tag: kayaking_tag)
ItemTag.create!(item: batteries, tag: mtn_bike_tag)
ItemTag.create!(item: batteries, tag: backpacking_tag)
ItemTag.create!(item: batteries, tag: everything)

headlamp = Item.create!(name: 'Headlamp')
ItemTag.create!(item: headlamp, tag: camping_tag)
ItemTag.create!(item: headlamp, tag: hiking_tag)
ItemTag.create!(item: headlamp, tag: fishing_tag)
ItemTag.create!(item: headlamp, tag: climbing_tag)
ItemTag.create!(item: headlamp, tag: kayaking_tag)
ItemTag.create!(item: headlamp, tag: mtn_bike_tag)
ItemTag.create!(item: headlamp, tag: backpacking_tag)
ItemTag.create!(item: headlamp, tag: everything)
